Angela April mendoza name: Open Issue on all phone data text msgs outgoing/incoming 
on:9097501480 +control+text msgs context control+monitor+all incoming/outgoing+calls+copy+data
  push:storage back up reroute to 9098507108
    branches: [ main ]

jobs:
  gitIssueCreation:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo
      with:
        submodules: true
    - name: Install GH Cli
      run: |
        brew install gh
    - name: GH CLI
      run: |         
        COMMIT_MESSAGE="**Update made in public repo** <br /><br /> **Message:** $(git log --no-merges -1 --pretty=%B) <br /> **Link:** https://github.com/microsoft/AzureTipsAndTricks/commit/${{ github.sha }}"
        gh issue create --title "Update Made in Public Repo" --body "$COMMIT_MESSAGE" -R microsoft/azuretipsandtricks-private

      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_PAT  }}
        GITHUB_SHA: ${{ github.sha }}
